FROM node:16-alpine AS client-build
RUN npm install -g @angular/cli@^12.0.4
COPY . ./src
WORKDIR /src/client
RUN npm i
RUN ng build

FROM node:16-alpine AS api-build
COPY . ./src
WORKDIR /src/server
RUN npm i
RUN npm run build

FROM node:16-alpine
WORKDIR /app
COPY --from=api-build /src/server/bundle .
COPY --from=client-build /src/client/dist/client ./public
CMD [ "node", "index.js"]